/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HousesRouteImport } from './routes/houses'
import { Route as ApiHousesRouteImport } from './routes/api/houses'
import { Route as HousesIdRouteImport } from './routes/houses_.$id'
import { Route as ApiHousesIdRouteImport } from './routes/api/houses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesRoute = HousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHousesRoute = ApiHousesRouteImport.update({
  id: '/api/houses',
  path: '/api/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIdRoute = HousesIdRouteImport.update({
  id: '/houses_/$id',
  path: '/houses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHousesIdRoute = ApiHousesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiHousesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/houses': typeof HousesRoute
  '/api/houses': typeof ApiHousesRouteWithChildren
  '/houses/$id': typeof HousesIdRoute
  '/api/houses/$id': typeof ApiHousesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/houses': typeof HousesRoute
  '/api/houses': typeof ApiHousesRouteWithChildren
  '/houses/$id': typeof HousesIdRoute
  '/api/houses/$id': typeof ApiHousesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/houses': typeof HousesRoute
  '/api/houses': typeof ApiHousesRouteWithChildren
  '/houses_/$id': typeof HousesIdRoute
  '/api/houses/$id': typeof ApiHousesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/houses' | '/api/houses' | '/houses/$id' | '/api/houses/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/houses' | '/api/houses' | '/houses/$id' | '/api/houses/$id'
  id:
    | '__root__'
    | '/'
    | '/houses'
    | '/api/houses'
    | '/houses_/$id'
    | '/api/houses/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HousesRoute: typeof HousesRoute
  ApiHousesRoute: typeof ApiHousesRouteWithChildren
  HousesIdRoute: typeof HousesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses': {
      id: '/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof HousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/houses': {
      id: '/api/houses'
      path: '/api/houses'
      fullPath: '/api/houses'
      preLoaderRoute: typeof ApiHousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses_/$id': {
      id: '/houses_/$id'
      path: '/houses/$id'
      fullPath: '/houses/$id'
      preLoaderRoute: typeof HousesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/houses/$id': {
      id: '/api/houses/$id'
      path: '/$id'
      fullPath: '/api/houses/$id'
      preLoaderRoute: typeof ApiHousesIdRouteImport
      parentRoute: typeof ApiHousesRoute
    }
  }
}

interface ApiHousesRouteChildren {
  ApiHousesIdRoute: typeof ApiHousesIdRoute
}

const ApiHousesRouteChildren: ApiHousesRouteChildren = {
  ApiHousesIdRoute: ApiHousesIdRoute,
}

const ApiHousesRouteWithChildren = ApiHousesRoute._addFileChildren(
  ApiHousesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HousesRoute: HousesRoute,
  ApiHousesRoute: ApiHousesRouteWithChildren,
  HousesIdRoute: HousesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
